#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

for i in 0/*.origin; do cp "$i" "${i%.origin}"; done

runApplication blockMesh
runApplication checkMesh
runApplication funkySetFields -time 0
runApplication decomposePar


#runApplication $application
#postProcess -func singleGraph-center
#postProcess -func singleGraph-west
#postProcess -func singleGraph-east
#------------------------------------------------------------------------------
