#!/bin/sh
#
#This is an example script to execute a parallel job with OpenFOAM
# ! Be sure to have decompose using decomposePar before submitting this script
#
#These commands set up the Grid Environment for your job:
# Output folder for the journal file
#PBS -o /nfs/home/ofoam3/OpenFOAM/projectSimulation 
#PBS -j oe
# Name of the job
#PBS - baseCase6Prcs 120000 cells 
#PBS -q batch
#PBS -l nodes=1:ppn=6:buddies
# E-mail address at which notification will be sent
#PBS -M ivan.lizat@outlook.de
#PBS -m abe

# Load OpenFOAM-6
source /nfs/etc/bashrc
OF60
# Change the current directory to the case directory
cd /nfs/home/ofoam/OpenFOAM/projectSimulation
# Execute interFoam on the current case directory
mpiexec cavitatingFoam -parallel > log.cavitatingFoam
